name: StormAchitecture
favicon: null
layout_spectrum: 0.959447551285848
typography_spectrum: 0.899547717301175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.49125829618424177
  lightness: 0.9847422277089208
  saturation: 0.31311786943115294
  rhythmicContrast: 0.7400258276611567
purpose: []
